name: generate-pacman

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man graph
        uses: Platane/snk@v3
        with:
          github_user_name: jovandosg
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push generated files to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Generated Pac-Man contribution graph"
          add: "output/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
